name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for reaching out to us, reach out to @bringback4fr on discord if no response in 72 hours."
        pr-message: "We are so honored to see you contributing to 3DSPal!"
